#! /bin/bash

#Copyright (c) 2018 by Cisco Systems, Inc.
#All rights reserved.

java -cp "TwitterEgoNetworkExtraction-0.0.1-SNAPSHOT.jar" com.rise.maven.TwitterEgoNetworkExtraction.GenerateAllDatasets $@
